levels:
  web:
    discovery:
      css:
        flags: ""
      html:
        flags: ""
      javascript:
        flags: ""
    tool:
      eslint:
        flags: ""
      htmllint:
        flags: ""
      jshint:
        flags: ""
      stylelint:
        flags: ""

  web_with_pylint:
    inherits_from: "web"
    discovery:
      python:
        flags: ""
    tool:
      pylint:
        flags: "--good-names=f,i,j,k,x,y,z,ex,_"
